### ISSUE TITLE
hyper ERROR: the out tar file is not exist

### ISSUE THREAD

**Issue by dhargitai** [hyperhq/hyperd#33] opened 2015-08-06 07:43 UTC
Hello,

I tried to build an image and got the following error:

``` console
hyper build -t image_name .
Sending build context to Docker daemon 365.7 MB
hyper ERROR: the out tar file is not exist
```

I'm on OSX 10.9.5 and I have Virtualbox 5.0. I also tried it with sudo and/or without giving a name for the image but I got the same result.

**Comment by carmark** [comment] 2015-08-06 08:28
Hi @dhargitai ,

Could you please provide more details, such as
* `hyper info` 
* Which image you want to build
* Dockerfile

Thanks,

**Comment by dhargitai** [comment] 2015-08-06 08:41
Hi @carmark,

Sure.

```console
$ hyper info
Images: 31
Containers: 0
PODs: 0
Storage Driver: vbox
Hyper Root Dir: /private/var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: VirtualBox
Total Memory: 10.0 GB
Operating System: Darwin Kernel Version 13.4.0
```

I'd like to build an image from this Dockerfile: https://gist.github.com/dhargitai/e6b9c74cfe64b25f42e2

**Comment by carmark** [comment] 2015-08-06 08:55
Thanks @dhargitai , I will try to reproduce and investigate this issue.

I will update once I have any finding.

**Comment by dhargitai** [comment] 2015-08-06 08:56
Thank you @carmark

**Comment by darylteo** [comment] 2015-08-06 14:22
I have the same issue here.

```
Images: 42
Containers: 2
PODs: 2
Storage Driver: vbox
Hyper Root Dir: /private/var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: VirtualBox
Total Memory: 8.0 GB
Operating System: Darwin Kernel Version 14.4.0
```

```
FROM php:5.6-apache
MAINTAINER Daryl Teo

COPY build.sh /
RUN chmod +x /build.sh

RUN /build.sh

COPY install.sh run.sh config_xdebug.sh /
RUN chmod +x /install.sh /run.sh /config_xdebug.sh
RUN /install.sh

ENV XDEBUG_PORT 9000

ENTRYPOINT ["/run.sh"]
CMD ["apache2-foreground"]
```

**Comment by carmark** [comment] 2015-08-13 11:08
@darylteo Could you please provide the `build.sh` script?

**Comment by darylteo** [comment] 2015-08-13 11:48
````
#!/bin/bash
set -e

apt-get update

# --- begin php setup --- #
echo 'Setting up PHP'

# --- end php setup --- #

# --- begin php extensions --- #

echo 'Setting up PHP extensions'

# gd installation
apt-get install -y \
	php5-gd \
	libjpeg62-turbo-dev \
	libpng12-dev

docker-php-ext-configure gd --with-jpeg-dir=/usr/include/
docker-php-ext-install gd

# xdebug
apt-get install -y \
	php5-xdebug

# mb_string required for mPDF library
docker-php-ext-install mbstring

# pdo mysql adaptor
docker-php-ext-install pdo_mysql

# # curl
# apt-get install -y libcurl
# docker-php-ext-install curl

# # recode
# apt-get install -y librecode-dev librecode0 php5-recode recode
# docker-php-ext-install recode


# docker-php-ext-install json
# docker-php-ext-install mysql
# docker-php-ext-install mysqli
# docker-php-ext-install pdo_mysql
# docker-php-ext-install pspell
# docker-php-ext-install readline
# docker-php-ext-install xsl

# --- end php extensions --- #
````

**Comment by carmark** [comment] 2015-08-13 13:20
@darylteo  @dhargitai 

Thanks for your support.

From your dockerfile, I doubt that this build fail may be caused by network issue, since both of you tried to install the additional package via `apt-get`.  I will do more test and investigation.

Regards,

**Comment by chr4** [comment] 2015-08-20 22:27
I can confirm this on osx/ virtualbox using even the simplest Dockerfiles:

```
$ cat Dockerfile
FROM ubuntu
CMD "echo hello"
```

```
$ hyper build .
Sending build context to Docker daemon 2.048 kB
hyper ERROR: the out tar file is not exist
```

**Comment by robinroestenburg** [comment] 2015-10-21 13:18
Same problem here, I get the same results from @chr4's minimal test.

Output from `hyper info`:

```
Images: 5
Containers: 0
PODs: 0
Storage Driver: vbox
  Root Dir: /private/var/lib/hyper/vbox
  Backing Filesystem: hfs+
Hyper Root Dir: /private/var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: vbox
Total Memory: 8.0 GB
Operating System: Darwin Kernel Version 14.5.0
```

**Comment by mckelvin** [comment] 2015-11-17 02:55
@chr4 +1

```
kelvin@PANs-MacBook-Pro:/tmp/reproduce » ls
Dockerfile
kelvin@PANs-MacBook-Pro:/tmp/reproduce » cat Dockerfile
FROM ubuntu:14.04
RUN ls
kelvin@PANs-MacBook-Pro:/tmp/reproduce » hyper info
Images: 5
Containers: 0
PODs: 0
Storage Driver: vbox
  Root Dir: /private/var/lib/hyper/vbox
  Backing Filesystem: hfs+
Hyper Root Dir: /private/var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: vbox
Total Memory: 8.0 GB
Operating System: Darwin Kernel Version 15.0.0
kelvin@PANs-MacBook-Pro:/tmp/reproduce » hyper build -t "reproduce-issue-33" .
Sending build context to Docker daemon 2.048 kB
hyper ERROR: the out tar file is not exist
```

Output of `xtail /var/log/hyper/hyperd*` while running `hyper build -t "reproduce-issue-33" .`: https://gist.github.com/mckelvin/010ff60c234def9cfde3


* * *

I uninstalled the hyper:

```

$ sudo /opt/hyper/bin/uninstall-hyper.sh --purge
VBoxManage: error: Machine 'hyper-mac-pull-vm' is not currently running
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
$ tree /private/var/lib/hyper
/private/var/lib/hyper
└── tar
```

and I'm sure no hyper/VirtualBox process was running via:

```
ps aux | grep hyper
ps aux | grep irtual
```

then reinstall again and again, but the issue still continues. :(

**Comment by robhicks** [comment] 2015-12-05 19:38
+1 
OSX 10.11.1
```
Images: 6
Containers: 0
PODs: 0
Storage Driver: vbox
  Root Dir: /private/var/lib/hyper/vbox
  Backing Filesystem: hfs+
Hyper Root Dir: /private/var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: vbox
Total Memory: 16.0 GB
Operating System: Darwin Kernel Version 15.0.0
```

**Comment by carmark** [comment] 2015-12-14 08:22
I have investigated this issue for a while, but got nothing.  With the latest source code from master branch, I did encounter other issues.  It looks like the hyper on Mac OSX with virtualbox has a long way to be product.  I will continue to fix the issues on Mac with VirtualBox.

Thanks,

**Comment by darylteo** [comment] 2015-12-14 12:58
I haven't followed the issue lately and moved away from docker for production use, but keep it up anyway!

**Comment by gnawux** [comment] 2017-03-15 09:32
close this issue, virtualbox support has been removed from the latest release

**Closed by gnawux** 2017-03-15 09:32 UTC
Labels: bug, virtualbox
