### ISSUE TITLE
Image pulled by the form of image@digest can't be removed

### ISSUE THREAD

**Issue by xlgao-zju** [hyperhq/hyperd#556] opened 2017-03-17 06:44 UTC
Image pulled by the form of image@digest can't be removed. And I can remove it by using `-f`.

```
xlgao@Joker:~/gocode/src/github.com/hyperhq/hyperd$ sudo ./hyperctl pull busybox@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e: Pulling from library/busybox
4b0bc1c4050b: Already exists 
Digest: sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
Status: Downloaded newer image for busybox@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e

xlgao@Joker:~/gocode/src/github.com/hyperhq/hyperd$ sudo ./hyperctl images
REPOSITORY                         TAG                 IMAGE ID            CREATED               VIRTUAL SIZE
busybox                            <none>              7968321274dc        2017-01-14 06:13:54   1.11 MB
gcr.io/google_containers/busybox   1.24                0cb40641836c        2016-01-16 02:06:41   1.114 MB

xlgao@Joker:~/gocode/src/github.com/hyperhq/hyperd$ sudo ./hyperctl rmi 7968321274dc
Error remove the image(7968321274dc): Error from daemon's response: conflict: unable to delete 7968321274dc (must be forced) - image is being used by stopped container 0b3b567ec59c
```

cc @feiskyer

**Comment by gnawux** [comment] 2017-03-17 06:46
but the message said it is used by container ```0b3b567ec59c```

**Comment by xlgao-zju** [comment] 2017-03-17 06:54
@gnawux I can't see any container, after I issued `hyperctl list container`. And I tried several times, I got different containerIDs.

**Comment by gnawux** [comment] 2017-03-17 06:56
could you try reproduce with other image with digest? If cannot, that should be an issue of container clean up.

**Comment by feiskyer** [comment] 2017-03-17 06:56
@gnawux: @xlgao-zju said it reports different container IDs when trying to remove the image.

**Comment by gnawux** [comment] 2017-03-17 07:30
@feiskyer @xlgao-zju  It might be issue of container cleanup as well... because too many tests use busybox image.

Just do a little more test with another image with digest (never pulled before), it will help to locate the issue.

**Comment by xlgao-zju** [comment] 2017-03-17 07:46
@gnawux I just tried other image@digest, it worked fine... So it maybe the issue of cleanup... :+1: So, should I close this issue?

**Comment by gnawux** [comment] 2017-03-17 07:47
@xlgao-zju not sure whether you should close it or change it to a issue for clean up...

**Comment by gnawux** [comment] 2017-03-17 07:53
@xlgao-zju I suggest you do another test:

- pull image without digest (only)
- pull the image with digest (same image, but ref with digest)
- run container with image:tag pair
- remove the container
- remove image without digest (only)
- remove image with digest

To see if there are cleanup issue with digest image

**Comment by gnawux** [comment] 2017-03-18 16:27
can not reproduce, will check and report if found similar issue

**Closed by gnawux** 2017-03-18 16:27 UTC
