### ISSUE TITLE
Portmapping rule iptables says "Bad IP address"

### ISSUE THREAD

**Issue by m-barthelemy** [hyperhq/hyperd#679] opened 2017-11-22 00:39 UTC
I'm using Hyperd 1.0, Debian Ubuntu package.
When creating a pod with a port mapping rule, I get:
```
Unable to setup NAT rule in HYPER chain: iptables failed: iptables --wait -t nat -I HYPER -p tcp -m tcp --dport 10000 -j DNAT --to-destination 192.168.123.8/24:10000: iptables v1.6.0: Bad IP address "192.168.123.8/24"
```

If I manually run the `iptables` command, replacing `--to-destination 192.168.123.8/24:10000` with `--to-destination 192.168.123.8:10000` (/24 removed), it works.

Is that a bug?

**Comment by m-barthelemy** [comment] 2017-12-12 23:12
Hi,
Is there anything I could do to help fixing this one? Any additional information I could provide?

**Comment by resouer** [comment] 2017-12-12 23:26
@m-barthelemy Are you using Kubernetes with hyperd my I ask? which version?

**Comment by m-barthelemy** [comment] 2017-12-13 00:44
Negative, I get that error using both `hyperctl` and Hyperd API.

**Comment by gnawux** [comment] 2017-12-13 10:37
@m-barthelemy looks like a bug, will check it.

**Comment by gnawux** [comment] 2017-12-13 10:43
@m-barthelemy did you manually configure the IP address of the container or pod?

**Comment by gnawux** [comment] 2017-12-13 10:51
@m-barthelemy I confirmed this is introduced [here](https://github.com/hyperhq/runv/commit/2e9a7596ebce8421c557fbcca15987c55c674cc7#diff-38ca951ac42fe398528410b26e3f6dbeR237) by hyperhq/runv#592 .

It will be fixed soon and add additional test for it.

**Comment by gnawux** [comment] 2017-12-14 06:34
#692 fixed the issue

@m-barthelemy if it is not fixed in your side, please reopen this issue.

**Closed by gnawux** 2017-12-14 06:34 UTC
