### ISSUE TITLE
Problem when compiling hyperd(for xen) from source

### ISSUE THREAD

**Issue by Ddnirvana** [hyperhq/hyperd#678] opened 2017-11-21 08:50 UTC
Hi, guys,

I am trying to use hyperd(or runv) in xen.
However, when I compile it, it fails.
The error logs are:
<pre>
dd@dd-PC3:~/devlop/gopath/src/github.com/hyperhq/hyperd$ make
Making all in cmd
make[1]: Entering directory `/home/dd/devlop/gopath/src/github.com/hyperhq/hyperd/cmd'
Making all in hyperd
make[2]: Entering directory `/home/dd/devlop/gopath/src/github.com/hyperhq/hyperd/cmd/hyperd'
go build -tags "static_build with_xen  exclude_graphdriver_btrfs libdm_no_deferred_remove" -ldflags "-X github.com/hyperhq/hyperd/utils.VERSION=1.0.0 -X github.com/hyperhq/hyperd/utils.GITCOMMIT=`git describe --dirty --always --tags 2> /dev/null || true`" hyperd.go
# github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/lib/runvxenlight
../../vendor/github.com/hyperhq/runv/lib/runvxenlight/xenlight.go:857: cannot use unsafe.Pointer(Ctx.logger) (type unsafe.Pointer) as type *C.struct_xentoollog_logger in argument to func literal
../../vendor/github.com/hyperhq/runv/lib/runvxenlight/xenlight.go:872: cannot use unsafe.Pointer(Ctx.logger) (type unsafe.Pointer) as type *C.struct_xentoollog_logger in argument to func literal
../../vendor/github.com/hyperhq/runv/lib/runvxenlight/xenlight.go:1173: cannot use cpath (type *C.char) as type unsafe.Pointer in argument to func literal
../../vendor/github.com/hyperhq/runv/lib/runvxenlight/xenlight.go:1193: cannot use cpath (type *C.char) as type unsafe.Pointer in argument to func literal
# github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/xen
../../vendor/github.com/hyperhq/runv/hypervisor/xen/xen.go:258:71: cannot use guest.Ipaddr[0] (type byte) as type string in argument to HyperxlNicAdd
make[2]: *** [build-hyperd] Error 2
make[2]: Leaving directory `/home/dd/devlop/gopath/src/github.com/hyperhq/hyperd/cmd/hyperd'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dd/devlop/gopath/src/github.com/hyperhq/hyperd/cmd'
make: *** [all-recursive] Error 1
</pre>

The domain0 and xen info is
<pre>
dd@dd-PC3:~/devlop/gopath/src/github.com/hyperhq/hyperd$ sudo xl info
host                   : dd-PC3
release                : 4.4.0-98-generic
version                : #121~14.04.1-Ubuntu SMP Wed Oct 11 11:54:55 UTC 2017
machine                : x86_64
nr_cpus                : 8
max_cpu_id             : 7
nr_nodes               : 1
cores_per_socket       : 4
threads_per_core       : 2
cpu_mhz                : 3408
hw_caps                : bfebfbff:77faf3ff:2c100800:00000121:0000000f:009c6fbf:00000000:00000100
virt_caps              : hvm hvm_directio
total_memory           : 16263
free_memory            : 261
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 9
xen_extra              : .0
xen_version            : 4.9.0
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          :
xen_commandline        : placeholder no-real-mode edd=off
cc_compiler            : gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
cc_compile_by          : dd
cc_compile_domain      :
cc_compile_date        : Sat Nov 11 18:30:37 CST 2017
build_id               : 8c108388c05212ed0c6ca799d31b8a4fc128cdc5
xend_config_format     : 4
</pre>

My go version is 
<pre>
go version go1.9.2 linux/amd64
</pre>

The hyperd codes I used are downloaded from the git, also, I have tried the latest version(v1.0.0) release and it ends with the same fail log...

Any advices are welcomed!! Thanks very much!

**Comment by gnawux** [comment] 2017-11-21 08:55
I am not sure whether it is the root cause, but xen 4.4 is not supported.

- For xen full virtualization, 4.5 at least;
- For xen paravirtualization, 4.9 at least;

**Comment by Ddnirvana** [comment] 2017-11-21 09:47
hi ,@gnawux. Thanks for your quickly response! But  `release                : 4.4.0-98-generic` actually is the version of the domain0 kernel, and the xen version I used is`xen_version            : 4.9.0`(You can also see this in the previous result of `xl info`)..

**Comment by gnawux** [comment] 2017-11-21 09:49
@Ddnirvana sorry, I mistake read the messages... Will take a further look soon.

**Comment by gnawux** [comment] 2017-11-21 11:20
@Ddnirvana checked and this is caused by golang cgo update. Will update the code for the compatible with latest go compiler.

**Comment by Ddnirvana** [comment] 2017-11-21 12:28
hi, @gnawux   Please notify me when you finish updating the code :) Thanks very much!

**Comment by gnawux** [comment] 2017-12-12 09:21
This is a bug introduced by hyperhq/runv#597 , and will be fixed soon.

It also affected #690

**Closed** 2017-12-13 07:53 UTC

**Comment by gnawux** [comment] 2017-12-13 08:01
@Ddnirvana xen build has been fixed on master, and this issue is auto closed by github. If you still suffer from this issue, you may reopen it.
